version: '2'
services:
#  zookeeper:
#    image: wurstmeister/zookeeper
#  kafka:
#    image: wurstmeister/kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  postgres:
    build: ./postgres
    ports:
      - 5432:5432
    volumes:
      - ./.postgres:/var/lib/postgresql/data
